config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'

  root 'pages#home'

  devise_for 	:users,
  						:path => '',
  						:path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'},
  						:controllers => {:omniauth_callbacks => 'omniauth_callbacks',
  														 :registrations => 'registrations'
  														}

  resources :users, only: [:show]
  resources :properties
  resources :photos

  resources :properties do
    resources :reservations, only: [:create]
  end

  resources :conversations, only: [:index, :create] do
      resources :messages, only: [:index, :create]
    end

  resources :properties do
    resources :reviews, only: [:create, :destroy]
  end

  get '/preload' => 'reservations#preload'
  get '/preview' => 'reservations#preview'

  get '/your_places' => 'reservations#your_places'
  get '/your_reservations' => 'reservations#your_reservations'

  post '/notify' => 'reservations#notify'
  post '/your_places' => 'reservations#your_places'

  get '/search' => 'pages#search'
end

app/models/property.rb
class Property < ActiveRecord::Base
  belongs_to :user
  has_many :photos
  has_many :reservations
  has_many :reviews

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  validates :property_type, presence: true
  validates :price, presence: true
  validates :accommodate, presence: true
  # validates :bedroom, presence: true
  validates :bathroom, presence: true
  validates :listing_name, presence: true, length: {maximum: 1000}
  validates :summary, presence: true, length: {maximum: 2000}
  validates :address, presence: true

  def average_rating
    reviews.count == 0 ? 0 : reviews.average(:star).round(2)
  end

  def show_first_photo(size)
    if self.photos.length == 0
      "treehouselogo.png"
    else
      self.photos[0].image.url(size)
    end
  end

end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:show, :edit, :update]
  before_action :authenticate_user!, except: [:show]

  def index
    @properties = current_user.properties
  end

  def show
    @photos = @property.photos

    @booked = Reservation.where("property_id = ? AND user_id = ?", @property.id, current_user.id).present? if current_user

    @reviews = @property.reviews
    @hasReview = @reviews.find_by(user_id: current_user.id) if current_user
  end

  def new
    @property = current_user.properties.build
  end

  def create
    @property = current_user.properties.build(property_params)

    if @property.save

      if params[:images]
        params[:images].each do |image|
          @property.photos.create(image: image)
        end
      end

      @photos = @property.photos
      redirect_to edit_property_path(@property), notice: "Saved..."
    else
      flash[:alert] = "Please provide all required information for this listing."
      render :new
    end
  end

  def edit
    if current_user.id == @property.user.id
      @photos = @property.photos
    else
      redirect_to root_path, notice: "You don't have permission."
    end
  end

  def update
    if @property.update(property_params)

      if params[:images]
        params[:images].each do |image|
          @property.photos.create(image: image)
        end
      end

      redirect_to edit_property_path(@property), notice: "Updated..."
    else
      flash[:alert] = "Please provide all required information for this property."
      render :edit
    end
  end

  private
    def set_property
      @property = Property.find(params[:id])
    end

    def property_params
      params.require(:property).permit(:property_type, :quarter, :semester, :room, :accommodate, :bedroom, :bathroom, :listing_name, :summary, :address, :is_tv, :is_kitchen, :is_ac, :is_heating, :is_internet, :is_furnished, :is_workspace, :is_dishwasher, :is_pet_allowed, :is_parking, :is_doorman, :is_roof_access, :is_gym, :is_pool, :price,
      :square_foot, :washer, :active)
    end
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/_form.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Create Your Place
  </div>
  <div class="panel-body">
    <div class="container">

      <%= form_for @property, html: {multipart: true} do |f| %>

      <div class="row">

          <div class="col-md-4 select">
            <div class="form-group">
              <label>Quarter (if applicable)</label>
            <%= f.select :quarter, [["Fall", "Fall"], ["Winter", "Winter"], ["Spring", "Spring"], ["Summer", "Summer"]], id: "quarter", prompt: "Select...", class: "form-control" %>
            </div>
          </div>

          <div class="col-md-4 select">
            <div class="form-group">
              <label>Semester (if applicable)</label>
            <%= f.select :semester, [["Fall", "Fall"], ["Spring", "Spring"], ["Summer", "Summer"]], id: "semester", prompt: "Select...", class: "form-control" %>
            </div>
          </div>

          <div class="col-md-4 select">
            <div class="form-group">
              <label>Property Type*</label>
            <%= f.select :property_type, [["Apartment", "Apartment"], ["House", "House"], ["Frat House", "Frat House"],
            ["Town House", "Town House"]], id: "property_type", prompt: "Select...", class: "form-control" %>
            </div>
          </div>

          <!-- <div class="col-md-4 select">
            <div class="form-group">
              <label>Rooms</label>
            <%= f.select :room, [["1", "1"], ["2", "2"], ["3", "3"],
            ["4", "4"], ["5", "5"], ["6", "6"],["7", "7"], ["8", "8"], ["9", "9"],
            ["10+", "10+"]], id: "room", prompt: "Select...", class: "form-control" %>
            </div>
          </div> -->

        <!-- <div class="col-md-3 select">
          <div class="form-group">
            <label>Bedrooms*</label>
          <%= f.select :accommodate, [["1", "1"], ["2", "2"], ["3", "3"],
          ["4", "4"], ["5", "5"], ["6", "6"],["7", "7"], ["8", "8"], ["9", "9"],
          ["10+", "10+"]], id: "accomodate", prompt: "Select...", class: "form-control" %>
          </div>
        </div> -->
      </div>

        <div class = "row">
          <!-- <div class="col-md-3 select">
            <div class="form-group">
              <label>Bedrooms*</label>
            <%= f.select :bedroom, [["1", "1"], ["2", "2"], ["3", "3"],
            ["4", "4"], ["5", "5"], ["6", "6"],["7", "7"], ["8", "8"], ["9", "9"],
            ["10+", "10+"]], id: "bedroom", prompt: "Select...", class: "form-control" %>
            </div>
          </div> -->
          <div class="col-md-3 select">
            <div class="form-group">
              <label>Bedrooms*</label>
            <%= f.select :accommodate, [["1", "1"], ["2", "2"], ["3", "3"],
            ["4", "4"], ["5", "5"], ["6", "6"],["7", "7"], ["8", "8"], ["9", "9"],
            ["10+", "10+"]], id: "accomodate", prompt: "Select...", class: "form-control" %>
            </div>
          </div>

          <div class="col-md-3 select">
            <div class="form-group">
              <label>Bathrooms*</label>
            <%= f.select :bathroom, [["1", "1"], ["1.5", "1.5"], ["2", "2"],
            ["2.5", "2.5"], ["3", "3"], ["3.5", "3.5"],["4", "4"], ["4.5", "4.5"], ["5", "5"],
            ["5+", "5+"]], id: "bathroom", prompt: "Select...", class: "form-control" %>
            </div>
          </div>

          <div class="col-md-3 select">
            <div class="form-group">
              <label>Laundry</label>
            <%= f.select :washer, [["In-Unit Laundry", "In-Unit Laundry"], ["Shared", "Shared"], ["None", "None"]], id: "washer", prompt: "Select...", class: "form-control" %>
            </div>
          </div>

          <div class="col-md-3">
            <div class="form-group">
              <label>Square Feet</label>
              <div class="input-group">
              <%= f.text_field :square_foot, placeholder: "eg. 1000", class: "form-control" %>
              <div class="input-group-addon">ft.</div>
              </div>
            </div>
          </div>

        </div>

        <div class="row">
          <div class="form-group">
            <label>Listing name*</label>
            <%= f.text_field :listing_name, placeholder: "Try to be clear", class: "form-control" %>
          </div>
        </div>

        <div class="row">
          <div class="form-group">
            <label>Summary*</label>
            <%= f.text_area :summary, rows: 5, placeholder: "Describe your place", class: "form-control" %>
          </div>
        </div>

        <div class="row">
          <div class="form-group">
            <label>Address*</label>
            <%= f.text_field :address, placeholder: "What is your address", class: "form-control" %>
          </div>
        </div>

        <div class="row">
          <div class="col-md=4">
            <div class="form-group">
              <%= f.check_box :is_tv %> TV
            </div>
            <div class="form-group">
              <%= f.check_box :is_ac %> Air Conditioning
            </div>
            <div class="form-group">
              <%= f.check_box :is_heating %> Heating
            </div>
            <div class="form-group">
              <%= f.check_box :is_internet %> Internet
            </div><div class="form-group">
              <%= f.check_box :is_furnished %> Furnished
            </div>
            <div class="form-group">
              <%= f.check_box :is_kitchen %> Kitchen
            </div>
            <div class="form-group">
              <%= f.check_box :is_workspace %> Workspace
            </div>
            <div class="form-group">
              <%= f.check_box :is_dishwasher %> Dishwasher
            </div>
            <div class="form-group">
              <%= f.check_box :is_pet_allowed %> Pets Allowed
            </div><div class="form-group">
              <%= f.check_box :is_parking %> Parking
            </div>
            <div class="form-group">
              <%= f.check_box :is_doorman %> Doorman
            </div><div class="form-group">
              <%= f.check_box :is_roof_access %> Roof Access
            </div>
            <div class="form-group">
              <%= f.check_box :is_gym %> Gym
            </div><div class="form-group">
              <%= f.check_box :is_pool %> Pool
            </div>
          </div>

          <div class="row">
            <div class="col-md-4">
              <div class="form-group">
                <label>Monthly Price*</label>
                <div class="input-group">
                <div class="input-group-addon">$</div>
                <%= f.text_field :price, placeholder: "eg. 100", class: "form-control" %>
                </div>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-md-4">
              <div class="form-group">
                <span class="btn btn-default btn-file">
                  <i class="fa fa-cloud-upload fa-lg"></i> Upload Photos
                  <%= file_field_tag "images[]", type: :file, multiple: true %>
                </span>
              </div>
            </div>
          </div>

          <div id="photos"><%= render 'photos/list' %></div>

          <div class="row">
            <div class = "form-group">
              <%= f.check_box :active %> Post Listing for Viewing
            </div>
          </div>

          <div class="actions">
            <%= f.submit "Save", class: "btn btn-primary" %>
          </div>

      <% end %>

    </div>
  </div>
</div>

app/views/properties/create.html.erb
<h1>Properties#create</h1>
<p>Find me in app/views/properties/create.html.erb</p>

app/views/properties/edit.html.erb
<%= render 'form' %>

app/views/properties/index.html.erb
<div class="row">
	<div class="col-md-3">
		<ul class="sidebar-list">
			<li class="sidebar-item"><%= link_to "Your Listing", properties_path, class: "sidebar-link active" %></li>
			<li class="sidebar-item"><%= link_to "Your Offers", your_reservations_path, class: "sidebar-link" %></li>
      <li class="sidebar-item"><%= link_to "Your Requests", your_places_path, class: "sidebar-link" %></li>
		</ul>
	</div>
	<div class="col-md-9">
		<div class="panel panel-default">
			<div class="panel-heading">
				Listings
			</div>
			<div class="panel-body">

				<% @properties.each do |property| %>
					<div class="row">
						<div class="col-md-2">
							<%= image_tag property.show_first_photo(:thumb) %>
						</div>
						<div class="col-md-7">
							<h4><%= link_to property.listing_name, property_path(property)%></h4>
						</div>
						<div class="col-md-3 right">
							<%= link_to "Update", edit_property_path(property), class: "btn btn-primary" %>
						</div>
					</div>
					<hr>
				<% end %>

			</div>
		</div>
	</div>
</div>

app/views/properties/new.html.erb
<%= render 'form' %>

app/views/properties/show.html.erb
<div class="panel panel-default">
	<div class="panel-body">

		<!-- Image -->
		<div class="row">
			<div class="col-md-12">
				<% if @property.photos.count > 0 %>
				<%= image_tag @photos[0].image.url(), class: "backgroundimages" if @photos.length > 0 %>
				<% else %>
				<%= image_tag "treehouselogo.png", class: "img-responsive" %>
				<% end %>
			</div>
		</div>

		<br>

		<!-- Main Info -->
		<div class="row">
			<div class="col-md-8">
				<div class="row">
					<div class="col-md-3 text-center">
						<%= image_tag avatar_url(@property.user), class: "img-circle avatar-large" %><br><br>
						<%= link_to @property.user.fullname, user_path(@property.user_id) %> <br> <%= "(click to message)"%>

					</div>

					<div class="col-md-9">
						<h4><%= @property.listing_name %></h4>
						<%= @property.address %>

						<div class="row text-center row-space-1">
							<div class="col-sm-4">
								<i class="fa fa-home fa-2x"></i>
							</div>
							<!-- <div class="col-sm-3">
								<i class="fa fa-users fa-2x"></i>
							</div> -->
							<div class="col-sm-4">
								<i class="fa fa-bed fa-2x"></i>
							</div>
							<div class="col-sm-4">
								<i class="fa fa-ship fa-2x"></i>
							</div>
						</div>

						<div class="row text-center">
							<div class="col-sm-4">
								<%= @property.property_type %>
							</div>
							<div class="col-sm-4">
								<%= pluralize(@property.accommodate, 'Bedroom') %>
							</div>
							<div class="col-sm-4">
								<%= @property.bathroom %> <%= @property.bathroom > 1? "Bathrooms" : "Bathroom" %>
							</div>
						</div>

					</div>
				</div>
			</div>

			<div class="col-md-4">
				<% if current_user == @property.user %>
					<%= "" %>
				<% else %>
				<%= render 'reservations/form' %>
				<%= "" %>
				<% end %>
			</div>
		</div>

		<!-- About -->
		<div class="row">
			<div class="col-md-12">
				<h2>About This Listing</h2>
				<p><%= @property.summary %></p>
			</div>
		</div>

		<!-- Amenities -->
		<div class="row">
			<div class="col-md-2">
				<p>Amentities</p>
			</div>
			<div class="col-md-10">
				<div class="row">
					<div class="col-md-6">
						<ul class="amenities">
							<li class="<%= 'text-line-through' if !@property.is_furnished %>">Furnished</li>
							<li class="<%= 'text-line-through' if !@property.is_kitchen %>">Kitchen</li>
							<li class="<%= 'text-line-through' if !@property.is_internet %>">Internet</li>
              <li class="<%= 'text-line-through' if !@property.is_heating %>">Heating</li>
  						<li class="<%= 'text-line-through' if !@property.is_ac %>">Air Conditioning</li>
              <li class="<%= 'text-line-through' if !@property.is_tv %>">TV</li>
              <li class="<%= 'text-line-through' if !@property.is_gym %>">Gym</li>
							<li class="<%= 'text-line-through' if !@property.washer %>"><%= @property.washer %></li>
						</ul>
					</div>
					<div class="col-md-6">
						<ul class="amenities">
						<li class="<%= 'text-line-through' if !@property.is_workspace %>">Workspace</li>
						<li class="<%= 'text-line-through' if !@property.is_dishwasher %>">Dishwasher</li>
            <li class="<%= 'text-line-through' if !@property.is_pet_allowed %>">Pets Allowed</li>
						<li class="<%= 'text-line-through' if !@property.is_parking %>">Parking</li>
            <li class="<%= 'text-line-through' if !@property.is_doorman %>">Doorman</li>
            <li class="<%= 'text-line-through' if !@property.is_roof_access %>">Roof Access</li>
						<li class="<%= 'text-line-through' if !@property.is_pool %>">Pool</li>
						<li class="<%= 'text-line-through' if !@property.square_foot %>"><%= @property.square_foot %> Square Ft.</li>
					</ul>
					</div>
				</div>
			</div>
		</div>

		<!-- Carousel -->
		<div class="row">
			<div class="col-md-10 col-md-offset-1">
				<div id="myCarousel" class="carousel slide" data-ride="carousel">

					<% if @photos %>
						<!-- Indicators -->
				    <ol class="carousel-indicators">
							<% @photos.each do |photo| %>
								<li data-target="#myCarousel" data-slide-to="<%= photo.id %>"></li>
							<% end %>
						</ol>
					<% end %>

				  <div class="carousel-inner" role="listbox">
				    <% if @photos %>
							<% @photos.each do |photo| %>
								<div class="item <%= 'active' if photo.id == @photos[0].id %>">
				          <%= image_tag photo.image.url() %>
				        </div>
							<% end %>
						<% end %>
				  </div>

				  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
				    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
				    <span class="sr-only">Previous</span>
				  </a>
				  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
				    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
				    <span class="sr-only">Next</span>
				  </a>
				</div>
			</div>
		</div>

		<br>
		<hr>

		<div class="row">
			<div class="col-md-12">
				<h3>Reviews <span id="average_rating"></span> (<%= @reviews.count %>)</h3>
				<div class="container">
					<div>
						<%= render 'reviews/form' if @booked && !@hasReview %>
					</div>
					<div>
						<%= render 'reviews/list' %>
					</div>
				</div>
			</div>
		</div>

		<div class="row">
			<div class="col-md-12">

				<div id="map"></div>

				<style>
#map {
        width: 100%;
        height: 400px;
     }
    		</style>
				<script>
			      function initMap() {
			        var mapDiv = document.getElementById('map');
			        var map = new google.maps.Map(mapDiv, {
			            center: {lat: <%=@property.latitude%>, lng: <%=@property.longitude%>},
			            zoom: 14
			        });
							var marker = new google.maps.Marker({
								position: new google.maps.LatLng(<%= @property.latitude %>, <%=@property.longitude %>),
								title: "Treehouse"
							});

							marker.setMap(map);
			      }
			  </script>
			  <script async defer
			        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAqYq1yXZcYlqT5VyLh2UR-BZkseMlMHXI&callback=initMap">
			  </script>

			</div>
		</div>
			<h3> Near by </hr>
			<div class="row">
					<% for property in @property.nearbys(10) %>

					<div class="col-md-4">
						<div class="panel panel-default">
							<div class="panel-heading preview">
								<%= image_tag property.show_first_photo(:medium) %>
							</div>
							<div class="panel-body">
								<%= link_to property.listing_name, property %><br>
								(<%= property.distance.round(2) %> miles away)
							</div>
						</div>
					</div>

					<% end %>
			</div>

	</div>
</div>

<script>
	$('#average_rating').raty({
		path: '/assets',
		readOnly: true,
		score: <%= @property.average_rating %>
	});
</script>

app/views/properties/update.html.erb
<h1>Properties#update</h1>
<p>Find me in app/views/properties/update.html.erb</p>